### ISSUE TITLE
Reload causes a crash

### ISSUE THREAD

**Issue by Etienne-Wattebled** [bergerhealer/BKCommonLib#41] opened 2017-08-28 20:31 UTC
##### Spigot version: 1.11.2

<hr>

#### Problem or bug:
When a reload is done, the BkCommonLib doesn't work and appears to be in red when a /plugin is done, we need to restart the server.

#### Expected behaviour:
BkCommonLib should stay in green when a /reload and a /plugins is done and should continue to work.

#### Steps to reproduce:
Just reload the server and do /plugins

**Comment by bergerkiller** [comment] 2017-09-01 19:22
Are you using MyWorlds? If that is the case, this build may fix it:

https://ci.mg-dev.eu/job/MyWorlds/14/

Otherwise can you post the error youre getting? I don't get any errors on /reload on my test server right now.

**Comment by Etienne-Wattebled** [comment] 2017-09-01 20:44
Hello,

I don't use MyWorls.

`[22:43:23] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.3.0
[22:43:23] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[22:43:23] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.12.1-v2-SNAPSHOT
[22:43:23] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on Spigot (git-Spigot-3fb9445-6e3cec8) : v1_11_R1 (Minecraft 1.11.2)
[22:43:23] [Server thread/INFO]: [BKCommonLib] [Network] Now using the ProtocolLib library to provide Packet Listener and Monitor support
[22:43:23] [Server thread/ERROR]: [BKCommonLib] An error occurred while enabling, the plugin will be disabled:
[22:43:23] [Server thread/ERROR]: [BKCommonLib] Encountered a critical error
[22:43:23] [Server thread/ERROR]: [BKCommonLib] Please, check for an updated version of BKCommonLib before reporting this bug!
[22:43:23] [Server thread/ERROR]: [BKCommonLib] java.lang.ExceptionInInitializerError
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:373)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.PacketFilterManager.initializePlayers(PacketFilterManager.java:946)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.PacketFilterManager.incrementPhases(PacketFilterManager.java:462)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:396)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler.addPacketListener(ProtocolLibPacketHandler.java:156)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.utils.PacketUtil.addPacketListener(PacketUtil.java:220)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:421)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:783)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:749)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.Bukkit.reload(Bukkit.java:540)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)
[22:43:23] [Server thread/ERROR]: [BKCommonLib] Caused by: java.lang.IllegalArgumentException: 'PROTOCOL' is already in use
[22:43:23] [Server thread/ERROR]: [BKCommonLib] java.lang.IllegalArgumentException: 'PROTOCOL' is already in use
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at io.netty.util.UniqueName.<init>(UniqueName.java:53)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at io.netty.util.AttributeKey.<init>(AttributeKey.java:47)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.netty.ChannelInjector.<clinit>(ChannelInjector.java:95)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:373)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.PacketFilterManager.initializePlayers(PacketFilterManager.java:946)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.PacketFilterManager.incrementPhases(PacketFilterManager.java:462)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:396)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler.addPacketListener(ProtocolLibPacketHandler.java:156)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.utils.PacketUtil.addPacketListener(PacketUtil.java:220)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:421)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:783)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:749)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.Bukkit.reload(Bukkit.java:540)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[22:43:23] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)
[22:43:23] [Server thread/INFO]: [BKCommonLib] Disabling BKCommonLib v1.12.1-v2-SNAPSHOT
`

**Comment by bergerkiller** [comment] 2017-09-02 22:07
I noticed this in the logs:
 Ambiguous plugin name `BKCommonLib' for files `plugins/BKCommonLib.jar' and `plugins/BKCommonLib-1.12.1-v1.jar' in `plugins'

Can you delete the duplicate BKCommonLib jar file and see if that fixes things? I'm not sure if it will influence it, but resource loading bugs have happened before because of this.

**Comment by bergerkiller** [comment] 2017-09-02 22:21
I did spot a potential bug with the tab controller packet listener. It was not un-registered on shutdown of BKCommonLib. I think this does not matter much (because protocollib disables too and will wipe all listeners), but just in case, a fix. https://ci.mg-dev.eu/job/BKCommonLib/185/

**Comment by Etienne-Wattebled** [comment] 2017-09-02 22:29
Hello,

I deleted the duplicate. Sorry, I did a lot of tests but the problem is not here.
http://textup.fr/219614Sj

With 184:
http://textup.fr/219616AL

With 185:
http://textup.fr/219620H8

Thanks :)

**Comment by bergerkiller** [comment] 2017-09-03 01:08
I could reproduce the issue on 1.11.2 myself. After updating ProtocolLib to the latest development build, the issue appears resolved. Can you check yourself whether reloading works correctly with the latest build of ProtocolLib? http://ci.dmulloy2.net/job/ProtocolLib/386/

It is probably a bug that has been fixed in ProtocolLib.

**Comment by Etienne-Wattebled** [comment] 2017-09-03 08:10
Hello,

I reload 1 time => it works
I reload more than 2 times => it doesn't work.

This build of ProcolLib resolves partially the issue.

**Comment by bergerkiller** [comment] 2017-09-03 10:44
I have contacted Slimedog with these errors, since they don't appear to originate from BKCommonLib. After disabling all listeners the error simple moved elsewhere, when sending packets instead. Hopefully he has advice for fixing it, or fixes it himself.

**Comment by Etienne-Wattebled** [comment] 2017-09-03 10:47
Hello,

So, there is a real bug ? I am don't have a mental problem ? Haha
Does BkCommonLib continue to need ProtocolLib ?
I am french I don't understand everything you say me but if I can understand I can use Bk without ProtocolLib? 

Thanks

**Comment by bergerkiller** [comment] 2017-09-03 12:21
Yes you can use BKCommonLib without protocollib. Protocollib is only needed if you have more plugins (other than BKCommonLIb) that play with the network protocol.

**Comment by bergerkiller** [comment] 2017-09-03 15:43
Closing this issue as it is caused by ProtocolLib. If you want to reload the server with ProtocolLib running, do so without any players logged in. That is, kick everyone off the server or tell everyone to leave, then use /reload in the server terminal. I have added a warning message for this. https://github.com/bergerhealer/BKCommonLib/commit/305b813aee8a02896605129aa7c30e0b33e1c25d

**Closed by bergerkiller** 2017-09-03 15:43 UTC
