### ISSUE TITLE
 Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

### ISSUE THREAD

**Issue by seyink** [bergerhealer/BKCommonLib#163] opened 2024-04-26 17:26 UTC
##### Spigot version: Paper-496 (MC: 1.20.4)

<hr>

#### Problem or bug:
`[BKCommonLib] Loading server plugin BKCommonLib v1.20.4-v4
[01:10:29] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[01:10:29] [Server thread/WARN]: java.lang.Exception
[01:10:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:261)
[01:10:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.util.CraftMagicNumbers.getItem(CraftMagicNumbers.java:191)
[01:10:29] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen44906a57.newInstance(Unknown Source)
[01:10:29] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen44906a57.invoke(Unknown Source)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.mountiplex.reflection.declarations.Template$StaticMethod$Converted.invoke(Template.java:1417)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.generated.net.minecraft.world.item.ItemStackHandle.newInstance(ItemStackHandle.java:29)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.bukkit.common.utils.RecipeUtil.<clinit>(RecipeUtil.java:34)
[01:10:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[01:10:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:421)
[01:10:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:412)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:171)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:86)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.bukkit.common.internal.CommonClasses.loadUtil(CommonClasses.java:79)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:59)
[01:10:29] [Server thread/WARN]: 	at BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:548)
[01:10:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[01:10:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[01:10:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[01:10:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[01:10:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
[01:10:29] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
[01:10:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[01:10:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[01:10:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by bergerkiller** [comment] 2024-04-26 17:44
Can't at the moment. It initializes old stuff because this library has to support all the way back to 1.8. It has no further impact on the server besides logging that warning.

**Comment by bbayu123** [comment] 2024-04-26 19:09
Closing: Not a bug, won't fix.

**Closed by bbayu123** 2024-04-26 19:09 UTC
Labels: D. wontfix

**Comment by bergerkiller** [comment] 2024-04-26 22:11
Well, I want to fix this at some point, but until Bukkit officially **deletes** the legacy api, its just extra work that doesn't have much benefit.

At the moment, BKCL's BlockData API largely replaces this deprecated mess, and Im already using that in most places.

Regardless, this issue was reported 2 or 3 times before, so at the very least it would be a duplicate.
