### ISSUE TITLE
Barrier model not loading

### ISSUE THREAD

**Issue by SimplyMerlin** [bergerhealer/BKCommonLib#87] opened 2020-01-10 21:15 UTC
##### Spigot version: 1.12.2

<hr>

**Comment by bbayu123** [comment] 2020-01-10 21:16
Known issue, whether nothing should be rendered or at least something is debatable.

**Comment by bbayu123** [comment] 2020-01-10 21:19
Will close due to duplicate of #46

**Closed** 2020-01-10 21:20 UTC
Labels: A. bug, B. duplicate
