### ISSUE TITLE
Won't build since spigot repo is missing in pom.xml

### ISSUE THREAD

**Issue by kalleswe** [bergerhealer/BKCommonLib#134] opened 2021-12-06 17:52 UTC
Won't build since spigot repo is missing in pom.xml

**Comment by kalleswe** [comment] 2021-12-06 17:53
adding repo in pom.xml accually downloads it and it seems to work to compile

**Comment by weeryan17** [comment] 2021-12-06 17:57
The spigot repo doesn't need to be added to the pom. Build tools needs to be ran. Running build tools will create the appropriate files in your .m2 folder for the dependencies needed to compile the project.

**Comment by bergerkiller** [comment] 2021-12-06 18:11
Hosting the spigot jar artifact violates mojangs eula. ^ is the only way, and is by design.

**Comment by bergerkiller** [comment] 2021-12-06 18:15
To be more specific, the Spigot API repo could probably be added. But its not really relevant since, to run all the tests, it must have the spigot server jar regardless.

**Comment by bbayu123** [comment] 2023-06-03 18:59
Closing issue, not an issue - as mentioned previously, run BuildTools if you want to build BKCommonLib.

**Closed by bbayu123** 2023-06-03 18:59 UTC
