### ISSUE TITLE
FramedMapUpdater takes 628% of server tick

### ISSUE THREAD

**Issue by Nety01** [bergerhealer/BKCommonLib#83] opened 2019-11-21 19:33 UTC
##### BkCommonLib version: 
1.14.4-v1
##### Spigot version: 
Paper 1.13.2

<hr>

#### Problem or bug: 
BKCommonLib takes too much of server tick, to be specific, 628% of tick takes BKCommonLib::Task: com.bergerkiller.bukkit.common.internal.CommonMapController.FramedMapUpdater (interval:1)

#### Expected behaviour: 
It doesn't take so much of tick

#### Steps to reproduce: 
If it could be caused by that, in the time of timings was collecting data, I used plugin ImageOnMap ( https://www.spigotmc.org/resources/imageonmap.26585/ ) and was placing and destroying a lot of item frames in a moment.

#### Screenshot of timings:
![timings](https://user-images.githubusercontent.com/42073765/69370259-eb948780-0c9d-11ea-9ac3-77f331eda8d5.PNG)

**Comment by bergerkiller** [comment] 2019-11-21 22:14
Hmn, what is 'a lot of item frames'? How large of an image display do I have to create for it to create such a lag spike? It might be caused by something specific ImageOnMap does, like adding and removing a lot of entities rapidly.

**Comment by Nety01** [comment] 2019-11-22 17:56
Again tried it, without using ImageOnMap and it looks like it's happening because of fast placing and destroying item frames. https://i.imgur.com/cpQ549N.mp4 Looked to the timings then and it was high

**Comment by bergerkiller** [comment] 2019-11-22 18:05
Thank you! I will look into what I can do to either debounce this so it doesn't do so much processing when an item frame changes frequently, or that the time spent processing goes down

**Comment by bergerkiller** [comment] 2019-11-22 18:21
Hmn it certainly doesn't occur with just a few entities on the server and a single wall of item frames. Any estimate how many item frames you have on the server on the world on which you did this placing and destroying/changing? And how many other entities? There's no good way to calculate this using vanilla commands, so hopefully you have some plugin that can show that for you like a lag monitoring plugin

**Comment by bergerkiller** [comment] 2019-11-22 18:24
I did a little commit history checking and found one commit that is in the v2 snapshot that is not in the v1 release that may seriously impact the performance of what you were experiencing (caches the item frames it knows about per world, rather than recomputing it): https://github.com/bergerhealer/BKCommonLib/commit/2589f029f1999962d76774ab2b2e89df557ce5ec#diff-3a1b13a14baf065f8df14eb11a5d8fc3

It is worth trying the v2 snapshot to see if there is any change in lag https://ci.mg-dev.eu/job/BKCommonLib/658/

**Comment by Nety01** [comment] 2019-11-23 20:32
So I tried the latest dev build (build 658) and was walking for like 5 minutes around my base (so I wasn't placing and destroying any block etc. just walking and flying) and the timings looks like that

![bu](https://user-images.githubusercontent.com/42073765/69484811-e53a1300-0e37-11ea-814c-a525347806cb.PNG)

In the area I was moving there's exactly 60 item frames in total and all of them has a image from ImageOnMap in them. (If it loaded my meme wall so the number is 
778 xd but I don't think it loaded it during that time)

**Comment by bergerkiller** [comment] 2019-11-24 18:54
@Nety01 I couldn't really reproduce it, but I did find a possible explanation for the high timings. When item frames are placed at a chunk border, it has to load the neighbouring chunk in order to detect a full display. This may be causing some unlucky performance issues in your case. I've added some additional timings to rule this out/in.

https://www.dropbox.com/s/7qrvu5lbcxxhx98/BKCommonLib-1.14.4-v2-SNAPSHOT.jar?dl=0

Can you run another timings and send the report? It should show additional entries 'chunk_load', 'update_frames' and 'refresh_displays'

**Comment by Nety01** [comment] 2019-11-25 17:07
Yeah sure. New version, new timings.

![bktimings](https://user-images.githubusercontent.com/42073765/69561831-58659580-0fae-11ea-89ff-52cd6f421e67.PNG)

**Comment by bergerkiller** [comment] 2019-11-25 18:34
Sorry for the back and forth, one more version to test. Ive littered timings all over the place to figure out where so much time is spent, since it wasn't the obvious one (chunk loading).

https://www.dropbox.com/s/7qrvu5lbcxxhx98/BKCommonLib-1.14.4-v2-SNAPSHOT-timings2.jar?dl=0

Hopefully this will pinpoint exactly what steps take long. Thanks for helping me out in finding the root cause by the way! :)

**Comment by Nety01** [comment] 2019-11-26 18:18
Yea I'm happy to help to get that fixed.

![bktimings](https://user-images.githubusercontent.com/42073765/69660849-7ea83580-1081-11ea-9cbd-ba3e1593933e.PNG)

**Comment by bergerkiller** [comment] 2019-11-26 19:59
woah so in the span of 9 tick updates it had 4299 item frame neighbour detections. Thats pretty crazy. Unless theres thousands of item frames on the server, that cannot be right. Ill look into it

**Comment by bergerkiller** [comment] 2019-11-26 20:20
So I'm noticing something in both previous timings reports: ![ScreenShot_2019-11-26 21-19-59](https://user-images.githubusercontent.com/957601/69669625-815f5680-1092-11ea-9940-1692ba5f44df.png)

In that short timeframe 3000 new entities are added. Are these all item frames? Is it possibly part of your meme wall? Or is something triggering the rapid spawning and respawning of a large number of entities for a couple ticks?

**Comment by Nety01** [comment] 2019-11-27 18:32
I don't think it's all item frames, I wasn't near to so much of item frames, except the meme wall. Something triggering rapid spawning and respawning a lot of entities, I don't have anything like that there as I know. But I also have there a lot of commands block (that weren't activated) and holograms (armor stands).

Maybe one way of "fix" would be the option to disable that item frame check in config?

**Comment by Nety01** [comment] 2019-11-27 18:33
Well, if it's not needed of course. I use it for LightCleaner plugin.

**Comment by bergerkiller** [comment] 2019-11-27 20:28
A config option might be the only way to work around it for now Im afraid. I prefer not to do this because right now, there is no config.yml for bkcommonlib, and it would be nice to keep it that way.

I'll first give optimizing this a try with below 2% tps peak as a goal, if I can't make that happen by optimizing the neighbour detection logic then I'll add a config.yml with an option to turn item frame handling off.

**Comment by bergerkiller** [comment] 2019-11-28 16:31
I've made further changes in what I suspect were the reasons for spending so much time updating item frames. This was:
- Eliminate use of BKCommonLib's NBT API in critical code, using NMS directly instead
- Avoid temporary objects/wrappers being created in some places
- Cache the item frames mapped to facing + coordinate, so not all item frames of a world need to be iterated to find clusters

There's a reduction in time spent in local testing, but since I never get such extreme results like you did, I'm not sure if this is enough to do it.

Have a try: https://www.dropbox.com/s/4bl6vsay9l2qnxt/BKCommonLib-1.14.4-v2-SNAPSHOT-timings3.jar?dl=0

If this still doesn't fix it, I'll add a config.yml + option so this can be worked around.

**Comment by Nety01** [comment] 2019-11-28 17:34
Hmm looks much better than before anyway

![bktimings](https://user-images.githubusercontent.com/42073765/69824914-a3c9af00-120d-11ea-8733-c62b68c17196.PNG)

**Comment by bergerkiller** [comment] 2019-11-28 23:57
I have a version ready that allows you to disable all this frame tiling logic, but I first need to test these changes on all versions of minecraft to make sure nothing broke by accident.

**Comment by bergerkiller** [comment] 2019-11-29 00:21
Committed the changes, you can try the build version here: https://ci.mg-dev.eu/job/BKCommonLib/659/

**Comment by Nety01** [comment] 2019-11-29 13:52
Alright thank you. So this shouldn't do any visible changes right? Also can I disable it when I use this plugin for LightCleaner?

**Comment by bergerkiller** [comment] 2019-11-29 14:10
The frame logic is only used by map displays, which isn't used by light cleaner. It also won't affect the ImageOnMap plugin, since it doesn't use BKCommonLib's map display api for rendering images.

The only plugin that might require this feature is https://www.spigotmc.org/resources/maplands.46404/

**Comment by bbayu123** [comment] 2020-01-10 21:22
Should I assume this is resolved?

**Comment by Nety01** [comment] 2020-01-10 21:30
For me yes

**Comment by bbayu123** [comment] 2020-01-10 21:31
Nice, then I shall close this.

**Closed** 2020-01-10 21:32 UTC
Labels: A. bug, D. resolved (requires updating)
