### ISSUE TITLE
Error while using Custom Dimensions

### ISSUE THREAD

**Issue by HMU59** [bergerhealer/BKCommonLib#111] opened 2020-12-10 08:02 UTC
##### Spigot version: Paper version git-Paper-316 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

<hr>

#### Steps to reproduce: Install BKCommonLib (V2 or V3) and CustomDimensions. Create a custom dimension and TP there

Error :

[08:57:36] [Server thread/ERROR]: [BKCommonLib] Unhandled exception occured in onPacketSending(PacketEvent) for BKCommonLib
java.lang.IllegalArgumentException: This dimension is not registered
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen22b4168a.getKey(GeneratedCodeInvoker$mplgen22b4168a.java) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen22b4168a.invoke(GeneratedCodeInvoker$mplgen22b4168a.java) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1606) ~[?:?]
	at com.bergerkiller.bukkit.common.conversion.type.HandleConversion.dimensionKeyFromDimensionManager(HandleConversion.java:555) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedMethodInvoker$mplgen1274e879.invoke(Unknown Source) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.type.AnnotatedConverter.convertInput(AnnotatedConverter.java:50) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.type.LazyConverter.convertInput(LazyConverter.java:60) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.type.DuplexConverter$DuplexAdapter.convertInput(DuplexConverter.java:251) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:47) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.TranslatorFieldAccessor.get(TranslatorFieldAccessor.java:62) ~[?:?]
	at com.bergerkiller.bukkit.common.protocol.CommonPacket.read(CommonPacket.java:96) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.lambda$handlePacketSend$10(VehicleMountHandler_BaseImpl.java:281) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.synchronizeAndQueuePackets(VehicleMountHandler_BaseImpl.java:353) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.handlePacketSend(VehicleMountHandler_BaseImpl.java:262) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonVehicleMountManager$3.onMonitorPacketSend(CommonVehicleMountManager.java:72) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor.onPacketSending(ProtocolLibPacketHandler.java:339) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:291) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:247) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:223) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1696) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:850) ~[patched_1.16.4.jar:git-Paper-316]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:835) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1895) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.CommandTeleport.a(CommandTeleport.java:144) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.CommandTeleport.a(CommandTeleport.java:107) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.CommandTeleport.lambda$a$7(CommandTeleport.java:41) ~[patched_1.16.4.jar:git-Paper-316]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[patched_1.16.4.jar:git-Paper-316]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:182) ~[patched_1.16.4.jar:git-Paper-316]
	at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[patched_1.16.4.jar:git-Paper-316]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-316]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2008) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1819) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1772) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-316]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-316]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[08:57:36] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutRespawn@561c5661[
    a=net.minecraft.server.v1_16_R3.DimensionManager@7fe58e24
    b=ResourceKey[minecraft:dimension / minecraft:test]
    c=7617920629036208403
    d=CREATIVE
    e=ADVENTURE
    f=false
    g=true
    h=true
  ]

**Comment by HMU59** [comment] 2020-12-21 22:38
@bergerkiller ?

**Comment by bergerkiller** [comment] 2020-12-21 22:39
I'm aware of the issue, but I'm in many places at the moment. Sorry for the delay though, this has been open for a while now

**Comment by bergerkiller** [comment] 2020-12-22 16:26
I've been trying to get custom dimensions to work but its been a pretty big failure. You're talking about https://www.spigotmc.org/resources/1-16-custom-dimensions.83731/ right?

Ive tried two datapacks (sky/shards) but both just cause internal server errors when trying to generate the world. What is your setup so I can replicate it?

**Comment by bergerkiller** [comment] 2020-12-22 16:34
This one works: https://www.planetminecraft.com/data-pack/floating-island-dimension-plains/

But no errors in console

**Comment by HMU59** [comment] 2021-01-02 11:33
> I've been trying to get custom dimensions to work but its been a pretty big failure. You're talking about https://www.spigotmc.org/resources/1-16-custom-dimensions.83731/ right?
> 
> Ive tried two datapacks (sky/shards) but both just cause internal server errors when trying to generate the world. What is your setup so I can replicate it?

Hello and thanks for your answer,

Yes, this is exactly the plugin i'm using. I'm on last release of PaperMC

**Comment by HMU59** [comment] 2021-01-02 11:33
> This one works: https://www.planetminecraft.com/data-pack/floating-island-dimension-plains/
> 
> But no errors in console

This one is in Vanilla, unfortunately custom dimensions via datapacks dont work in Spigot/Paper without this plugin

**Comment by bergerkiller** [comment] 2021-01-02 13:18
Well what datapack are you using? That's what I need to know, as it appears some just don't work on spigot servers

**Comment by HMU59** [comment] 2021-01-03 05:21
> Well what datapack are you using? That's what I need to know, as it appears some just don't work on spigot servers

I'm using a homemade Vanilla datapack, which contain dimension and dimension type in .json format (like in Vanilla servers)

The plugin just handle the dimensions for Spigot/Paper because the don't do it by default

Dimension : 

{
  "generator": {
    "type": "minecraft:flat",
    "settings": {
      "biome": "minecraft:the_void",
      "layers": [],
      "structures": {
        "structures": {}
      }
    }
  },
  "type": "snow:snow"
}

Dimension type "snow:snow" : 

{
    "name": "snow:snow",
    "ultrawarm": false,
    "natural": true,
    "piglin_safe": false,
    "respawn_anchor_works": false,
    "bed_works": true,
    "has_raids": false,
    "has_skylight": true,
    "has_ceiling": false,
    "coordinate_scale": 1,
    "ambient_light": 0,
    "logical_height": 256,
    "effects": "minecraft:overworld",
    "infiniburn": "minecraft:infiniburn_overworld"
}

**Comment by HMU59** [comment] 2021-01-07 02:22
@bergerkiller Any news ? Thanks

**Comment by bergerkiller** [comment] 2021-01-07 02:39
Didnt see your previous reply yet, sorry, Im a bit all over the place. What do I do with the two json blocks? Save it as a file in a zip file?

**Comment by HMU59** [comment] 2021-01-07 03:51
> Didnt see your previous reply yet, sorry, Im a bit all over the place. What do I do with the two json blocks? Save it as a file in a zip file?

@bergerkiller 
Download this :
http://www.hmu59.fr/snow.zip

It contain a .zip datapack ; activate it on a Paper Server with the CustomDimensions plugin and you will replicate the bug.

To trigger the error in console, juste TP yourself in the "snow" custom dimension with the command :

/execute in snow:snow run tp @s 0 0 0

(in creative and while flying)

Let me know, thanks

**Comment by bergerkiller** [comment] 2021-01-07 03:53
Thanks, that should get me started. Its a bit late right now but after work Ill look into this some more

**Comment by HMU59** [comment] 2021-01-07 09:56
> Thanks, that should get me started. Its a bit late right now but after work Ill look into this some more

Thanks a lot ! I'm waiting :)

**Comment by bergerkiller** [comment] 2021-01-07 17:13
Can reproduce, I'll see if I can fix this properly

**Comment by HMU59** [comment] 2021-01-07 17:25
> Can reproduce, I'll see if I can fix this properly

Thanks ! I hope so :)

**Comment by bergerkiller** [comment] 2021-01-07 19:41
I've made <a> fix but I dont know what impact it has. Looks like something isnt done right internally, as the dimension isnt registered in the registry. It seems to only exist at world initialization. This might be a quirk of the CustomDimensions plugin.

A workaround of looping through the worlds and matching the dimension manager that way is how I've fixed it for now.

More will be added later to help with performance, as this is a little slow/risky on other threads. But you can already check if it fixes the error on your end.
https://github.com/bergerhealer/BKCommonLib/commit/ff41954d0128d95fa7b1f68f04f496cbb6e212e4

https://ci.mg-dev.eu/job/BKCommonLib/984/

**Comment by bergerkiller** [comment] 2021-01-10 00:33
A more definite commit. https://github.com/bergerhealer/BKCommonLib/commit/1dd6d038daf2332b632647577845e8edcf7fecff

https://ci.mg-dev.eu/job/BKCommonLib/985/

**Comment by HMU59** [comment] 2021-01-10 07:26
> A more definite commit. [1dd6d03](https://github.com/bergerhealer/BKCommonLib/commit/1dd6d038daf2332b632647577845e8edcf7fecff)
> 
> https://ci.mg-dev.eu/job/BKCommonLib/985/

Thank you, you are are amazing ! I'll test it today or tomorrow and i'll let you know

**Comment by bergerkiller** [comment] 2021-02-14 17:00
Any update on this with latest bkcommonlib release on spigot?

**Comment by bergerkiller** [comment] 2021-12-14 19:44
As of right now, it no longer even uses ResourceKey<DimensionManager> since that idiom has been removed as of Minecraft 1.18. So this issue ticket is now pretty much moot. There were only a few 1.16 versions which still use it, but not 1.16.5 which I would assume most people use. So I'm closing it.

**Closed by bergerkiller** 2021-12-14 19:44 UTC
